pubspec.yaml
name: flutter_book
description: flutter_book
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  scoped_model: 1.0.1
  sqflite: 1.1.2
  path_provider: 0.5.0+1
  flutter_slidable: 0.4.9
  intl: 0.15.7
  image_picker: 0.4.12+1
  table_calendar: ^3.0.0
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true